name: Docker Backend

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches:
      - main
      - 'release-*'
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches:
      - main
      - 'release-*'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: icr.io
  # Use ICR_NAMESPACE for main branches else use github repo name for PRs
  IMAGE_NAME: ${{ secrets.ICR_NAMESPACE || github.repository }}


jobs:
  # Calling reusable workflow
  call-fetch-go-version:
    uses: ./.github/workflows/fetch-go-version.yml

  build:
    runs-on: ubuntu-latest
    needs: call-fetch-go-version
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    outputs:
      image-tag: ${{ steps.image_tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ICR_USERNAME }}
          password: ${{ secrets.ICR_APIKEY }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./api
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GO_VERSION=${{ needs.call-fetch-go-version.outputs.go-version }}

      - name: Extract primary image tag
        id: image_tag
        run: |
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Save image to tar
        if: github.event_name == 'pull_request'
        run: |
          docker save "${{ steps.image_tag.outputs.tag }}" -o image.tar

      - name: Upload image tar
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: image-tar
          path: image.tar

  image-scan:
    needs: build
    uses: ./.github/workflows/license-scan.yml
    with:
      image: 'api'
      tag: ${{ needs.build.outputs.image-tag }}
      skip-image-build: true

